window.__CV_APP = window.__CV_APP || {};

window.__CV_APP.CV = {
  firstName: 'Najeeb',
  lastName: 'Almusawi',
  fullName: 'Najeeb Murtadha Abdulmohsen Almusawi',
  displayName: 'Najeeb Almusawi',
  email: 'najeebxalmusawi@gmail.com',
  phone: '+966568199827',
  phoneClean: '966568199827',
  phoneLocal: '0568199827',
  nationalId: '1112191778',
  dob: '2001-01-02',
  dobSlash: '01/02/2001',
  dobDay: '02',
  dobMonth: '01',
  dobYear: '2001',
  city: 'Al-Ahsa',
  cityAr: 'الأحساء',
  region: 'Eastern Province',
  regionAr: 'المنطقة الشرقية',
  country: 'Saudi Arabia',
  countryAr: 'السعودية',
  countryCode: 'SA',
  address: 'Building No. 3754, Street: Kharash Al Kalbi Alsaluli, District: Ar Rashidyah 1st, Postal Code: 36342',
  postalCode: '36342',
  shortAddress: 'FMAH3754',
  fullLocation: 'Al-Ahsa, Eastern Province, Saudi Arabia',
  university: 'King Faisal University',
  universityAr: 'جامعة الملك فيصل',
  degree: 'Bachelor of Computer Information Systems',
  degreeAr: 'بكالوريوس نظم المعلومات الحاسوبية',
  gpa: '2.53',
  gpaScale: '4.0',
  graduationDate: '2026-12-07',
  graduationYear: '2026',
  portfolio: 'https://xXNJEEBXx.github.io/my_website',
  linkedin: 'https://www.linkedin.com/in/najeeb-almusawi-16516417b',
  github: 'https://github.com/xXNJEEBXX',
  arabicLevel: 'Professional',
  englishLevel: 'Upper Intermediate',
  noticePeriod: '2 weeks',
  trainingPeriod: '6 months starting June 7, 2026',
  desiredSalary: '4000',
  summary: '5 years of freelance web development experience (HTML, CSS, JavaScript, PHP, MySQL), 3 years with React and Laravel, and 1 year at vibcoding. Highly adaptable and eager to learn. Actively seeking a 6-month hybrid Co-op placement starting from the upcoming summer.',
  responsibilities: 'Designed and developed responsive web applications using HTML5, CSS3, JavaScript, React.js, and Laravel. Built and maintained RESTful APIs with PHP and Node.js. Managed MySQL databases and implemented CRUD operations. Deployed projects using Git/GitHub and handled CI/CD pipelines. Collaborated with clients to gather requirements and deliver solutions on time.',
  jobTitle: 'Independent Software Developer',
  companyName: 'Freelance / Self-Employed',
  startDate: '01/01/2020',
  endDate: '',
  certificateName: '',
  issuingOrg: '',
  languageNative: 'Arabic',
  languageSecond: 'English',
  links: [
    'https://www.linkedin.com/in/najeeb-almusawi-16516417b',
    'https://github.com/xXNJEEBXX',
    'https://xXNJEEBXx.github.io/my_website'
  ],
  coverLetterFileName: 'KFU COOP Letter.pdf',
  mainSkills: 'HTML5, CSS, JavaScript, PHP, React.js, Laravel, MySQL, RESTful APIs, Full-Stack, GitHub & Git',
  otherSkills: 'Microsoft Office, VibeCoding, Agile, Docker, Node.js, AWS, Automation, Next.js, TypeScript, Express.js',
  nationality: 'Saudi',
  nationalityAr: 'سعودي',
  gender: 'Male',
  genderAr: 'ذكر',
};

const CV = window.__CV_APP.CV;

window.__CV_APP.PLATFORM_SELECTORS = {
  greenhouse: {
    '#first_name': CV.firstName, '#last_name': CV.lastName, '#email': CV.email, '#phone': CV.phone,
    'input[name="job_application[location]"]': CV.fullLocation, '#job_application_location': CV.fullLocation,
    'input[autocomplete="url"]': CV.portfolio,
  },
  smartrecruiters: {
    'input[name="firstName"]': CV.firstName, 'input[name="lastName"]': CV.lastName, 'input[name="email"]': CV.email,
    'input[name="phoneNumber"]': CV.phone, 'input[name="location"]': CV.fullLocation, 'input[name="currentCompany"]': CV.university,
  },
  zenats: {
    'input[name*="first"]': CV.firstName, 'input[name*="last"]': CV.lastName, 'input[name*="email"]': CV.email,
    'input[name*="phone"]': CV.phone, 'input[name*="city"]': CV.city, 'input[name*="mobile"]': CV.phone,
  },
  oracle_hcm: {
    'input[id*="FirstName"]': CV.firstName, 'input[id*="LastName"]': CV.lastName, 'input[id*="Email"]': CV.email,
    'input[id*="Phone"]': CV.phone, 'input[id*="City"]': CV.city, 'input[id*="PostalCode"]': CV.postalCode,
  },
  lever: {
    'input[name="name"]': CV.displayName, 'input[name="email"]': CV.email, 'input[name="phone"]': CV.phone,
    'input[name="org"]': CV.university, 'input[name="urls[LinkedIn]"]': CV.linkedin, 'input[name="urls[GitHub]"]': CV.github,
    'input[name="urls[Portfolio]"]': CV.portfolio,
  },
  workday: {
    'input[data-automation-id="legalNameSection_firstName"]': CV.firstName, 'input[data-automation-id="legalNameSection_lastName"]': CV.lastName,
    'input[data-automation-id="email"]': CV.email, 'input[data-automation-id="phone-number"]': CV.phoneClean,
    'input[data-automation-id="addressSection_city"]': CV.city, 'input[data-automation-id="addressSection_postalCode"]': CV.postalCode,
  },
  jarir: {
    'input[name="fn"]': CV.firstName, 'input[name="mn"]': 'Murtadha', 'input[name="ln"]': CV.lastName,
    'input[name="em"]': CV.email, 'input[name="mno"]': CV.phoneClean, 'input[name="hcno"]': CV.nationalId,
    'input[name="zcode"]': CV.postalCode, 'input[name="edu_institute_en_1"]': CV.university, 'input[name="edu_major_en_1"]': CV.degree,
  },
  workable: {
    'input[name="firstname"]': CV.firstName, 'input[name="lastname"]': CV.lastName, 'input[name="email"]': CV.email,
    'input[name="phone"]': CV.phone, 'input[name="address"]': CV.city,
  },
};

window.__CV_APP.FIELD_PATTERNS = [
  { pattern: /first.?name|fname|\bfn\b|given.?name|الاسم.?الأول/i, value: CV.firstName },
  { pattern: /last.?name|lname|\bln\b|family.?name|surname|اسم.?العائلة/i, value: CV.lastName },
  { pattern: /full.?name|الاسم.?الكامل|your.?name/i, value: CV.displayName, exclude: /first|last|user|company|middle/ },
  { pattern: /middle.?name|\bmn\b/i, value: 'Murtadha' },
  { pattern: /e.?mail|\bem\b|البريد/i, value: CV.email },
  { pattern: /phone|mobile|tel|\bmno\b|هاتف|جوال/i, value: CV.phone },
  { pattern: /city|مدينة/i, value: CV.city, exclude: /country|state/ },
  { pattern: /country|بلد|دولة/i, value: CV.country },
  { pattern: /state|province|region|منطقة|ولاية/i, value: CV.region },
  { pattern: /postal|zip|postcode|الرمز.?البريدي/i, value: CV.postalCode },
  { pattern: /address|عنوان/i, value: CV.address, exclude: /email|e.?mail|ip/ },
  { pattern: /university|جامعة|school|institution|مؤسسة/i, value: CV.university },
  { pattern: /degree|الدرجة|qualification/i, value: CV.degree },
  { pattern: /gpa|المعدل|grade/i, value: CV.gpa },
  { pattern: /graduation|تخرج/i, value: CV.graduationYear },
  { pattern: /linkedin/i, value: CV.linkedin },
  { pattern: /github/i, value: CV.github },
  { pattern: /portfolio|website|موقع/i, value: CV.portfolio, exclude: /company/ },
  { pattern: /responsibilities|المسؤوليات|duties|job.?description|وصف/i, value: CV.responsibilities, exclude: /team|project.?name/ },
  { pattern: /summary|about|why|نبذة|ملخص|cover.?letter/i, value: CV.summary },
  { pattern: /national.?id|هوية|رقم.?الهوية|id.?number/i, value: CV.nationalId },
  { pattern: /nationality|جنسية/i, value: CV.nationality },
  { pattern: /salary|راتب|مكافأة/i, value: CV.desiredSalary },
  { pattern: /job.?title|title|المسمى/i, value: CV.jobTitle },
  { pattern: /employer|company|الشركة/i, value: CV.companyName },
  { pattern: /start.?date|من.?تاريخ/i, value: CV.startDate },
  { pattern: /issuing|جهة|organization/i, value: CV.issuingOrg },
  { pattern: /language|لغة/i, value: CV.languageNative },
  { pattern: /notice.?period/i, value: CV.noticePeriod },
  { pattern: /experience|خبرة/i, value: '5' },
  { pattern: /skill|مهار/i, value: CV.mainSkills },
  { pattern: /date.?of.?birth|birth.?date|تاريخ.?الميلاد|dob/i, value: CV.dob },
  { pattern: /gender|sex|الجنس|النوع/i, value: CV.gender },
];

window.__CV_APP.SELECT_SYNONYMS = {
  [CV.country]: ['saudi', 'ksa', 'arabia', 'السعودية'],
  [CV.nationality]: ['saudi', 'سعودي', 'saudian'],
  [CV.gender]: ['male', 'm', 'ذكر'],
  [CV.university]: ['king faisal', 'kfu', 'فيصل'],
  [CV.degree]: ['bachelor', 'bs', 'bsc', 'undergrad', 'بكالوريوس'],
};
